bluetti:
  server:
    sso: 'https://sso.bluettipower.com'
    gateway: 'https://gw.bluettipower.com'
    app-key: 19974c15bccbc91b21a8ba71bf5
  oauth:
    client-id: HomeAssistant
    client-secret: SG9tZUFzc2lzdGFudA==